const groupedPlaces = [
  // 1 - 20
  [
    "Kumana National Park",
    "Gal Oya National Park",
    "Lahugala Kitulana National Park",
    "Kudumbigala Monastery (Sanctuary)",
    "Maduru Oya National Park (border region access)",
    "Arugam Bay",
    "Okanda Beach",
    "Panama Beach",
    "Oluvil Beach",
    "Crocodile Rock",
    "Nuwaragala Mountain",
    "Deeghawapi Raja Maha Viharaya",
    "Buddhangala Raja Maha Viharaya",
    "Rajagala Archaeological Reserve",
    "Muhudu Maha Viharaya",
    "Jaya Sri Maha Bodhi",
    "Ruwanwelisaya",
    "Jetavanaramaya",
    "Abhayagiri Monastery",
    "Thuparamaya"
  ],

  // 21 - 40
  [
    "Isurumuniya Temple",
    "Mihintale",
    "Samadhi Buddha Statue",
    "Kuttam Pokuna",
    "Lovamahapaya",
    "Wilpattu National Park",
    "Kala Wewa",
    "Tissa Wewa",
    "Nachchaduwa Wewa",
    "Ritigala Forest Monastery",
    "Isinbassagala Rajamaha viharaya",
    "Ella Rock",
    "Little Adam's Peak",
    "Nine Arches Bridge",
    "Diyaluma Falls",
    "Dunhinda Falls",
    "Ravana Falls",
    "Ravana Cave",
    "Lipton's Seat",
    "Adisham Bungalow"
  ],

  // 41 - 60
  [
    "Bogoda Wooden Bridge",
    "Mahiyanganaya Temple",
    "Dambatenne Tea Factory",
    "Beragala View Point",
    "Namunukula Mountain Range",
    "Dhowa Rock Temple",
    "Batticaloa Lagoon",
    "Pasikuda Beach",
    "Kalkudah Beach",
    "Batticaloa Fort",
    "Kallady Bridge",
    "Thiruchendur Murugan Temple",
    "Unnichchai Tank",
    "Vakarai Beach",
    "Kokkadicholai Thaanthonreeswarar Temple",
    "Navalady Beach",
    "Mandur Sri Kandaswamy Temple",
    "Eravur Beach",
    "Kiran Lagoon",
    "Galle Face Green"
  ],

  // 61 - 80
  [
    "Gangaramaya Temple",
    "Viharamahadevi Park",
    "Independence Square",
    "Colombo National Museum",
    "Dutch Hospital Shopping Precinct",
    "Beira Lake",
    "Mount Lavinia Beach",
    "Lotus Tower",
    "Pettah Market",
    "Arcade Independence Square",
    "Port City Colombo",
    "Dehiwala Zoo",
    "Marine Drive",
    "Galle Fort",
    "Unawatuna Beach",
    "Jungle Beach",
    "Hikkaduwa Beach",
    "Hikkaduwa Coral Reef",
    "Japanese Peace Pagoda (Rumassala)",
    "Galle Lighthouse"
  ],

  // 81 - 100
  [
    "Dutch Reformed Church",
    "Koggala Lake",
    "Martin Wickramasinghe Folk Museum",
    "Sea Turtle Hatchery Hikkaduwa",
    "Midigama Beach",
    "Ahangama Beach",
    "Kabalana Beach",
    "Rumassala Hill",
    "Negombo Beach",
    "Negombo Lagoon",
    "Muthurajawela Marsh",
    "Dutch Canal Negombo",
    "St. Mary's Church Negombo",
    "Angurukaramulla Temple",
    "Guruge Nature Park",
    "Kelaniya Raja Maha Viharaya",
    "Ja-Ela Wetlands",
    "Attanagalla Raja Maha Viharaya",
    "Negombo Dutch Fort Ruins",
    "Aviation Museum Sri Lanka"
  ],

  // 101 - 120
  [
    "Minuwangoda Rural Temple Circuit",
    "Seeduwa Wetland Bird Watching Areas",
    "Yala National Park",
    "Bundala National Park",
    "Mirijjawila Botanical Garden",
    "Hambantota Salt Pans",
    "Tangalle Beach",
    "Rekawa Beach",
    "Kalametiya Bird Sanctuary",
    "Ridiyagama Safari Park",
    "Mulkirigala Rock Temple",
    "Ussangoda National Park",
    "Hummanaya Blow Hole",
    "Kudawella Harbour",
    "Talalla Beach",
    "Godawaya Beach",
    "Jaffna Fort",
    "Nallur Kandaswamy Kovil",
    "Casuarina Beach",
    "Delft Island"
  ],

  // 121 - 140
  [
    "Nagadeepa Purana Viharaya",
    "Keerimalai Hot Springs",
    "Jaffna Public Library",
    "Point Pedro Lighthouse",
    "Kadurugoda Viharaya",
    "Charty Beach",
    "Kankesanthurai Beach",
    "Kayts Island",
    "Karainagar Beach",
    "Maviddapuram Kandaswamy Temple",
    "Jaffna Lighthouse",
    "Kalutara Bodhiya",
    "Kalutara Beach",
    "Richmond Castle",
    "Fa-Hien Cave",
    "Bentota Beach",
    "Bentota River Safari",
    "Brief Garden",
    "Lunuganga Estate",
    "Thudugala Ella"
  ],

  // 141 - 160
  [
    "Beruwala Lighthouse",
    "Moragalla Beach",
    "Panadura Beach",
    "Kande Viharaya",
    "Aluthgama Riverfront",
    "Kalido Beach",
    "Temple of the Sacred Tooth Relic",
    "Kandy Lake",
    "Royal Botanical Gardens Peradeniya",
    "Udawattakele Forest Reserve",
    "Knuckles Mountain Range",
    "Hanthana Mountain Range",
    "Victoria Dam",
    "International Buddhist Museum",
    "Sri Lanka Tea Museum",
    "Degaldoruwa Cave Temple",
    "Hunnasgiriya View Point",
    "Bahirawakanda Vihara Buddha Statue",
    "Ambuluwawa Tower",
    "Galagedara Temple"
  ],

  // 161 - 180
  [
    "Pinnawala Elephant Orphanage",
    "Pinnawala Zoo",
    "Kitulgala Adventure Area",
    "Belilena Cave",
    "Aberdeen Falls",
    "Alagalla Mountain Range",
    "Aranayake Forest Reserve",
    "Bopath Ella Waterfall",
    "Dedigama Kotavehera Temple",
    "Deraniyagala Rainforest Area",
    "Warakapola Rural Temple Circuit",
    "Rambukkana Railway Scenic Route",
    "Galigamuwa Temple Area",
    "Iranamadu Tank",
    "Kilinochchi War Memorial",
    "Elephant Pass",
    "Kanagambikai Amman Temple",
    "Paranthan Junction War Memorial Area",
    "Vattakachchi Lagoon",
    "Chundikkulam National Park"
  ],

  // 181 - 200
  [
    "Kilinochchi Town Park",
    "Akkarayankulam Tank",
    "Skandapuram Temple Area",
    "Pooneryn Lagoon",
    "Elephant Pass Lagoon",
    "Karachchi Area Monuments",
    "Kandawalai Rural Heritage Sites",
    "Ridi Viharaya",
    "Athugala Rock",
    "Kurunegala Lake",
    "Yapahuwa Rock Fortress",
    "Panduwasnuwara Ancient City",
    "Dambadeniya Kingdom Ruins",
    "Arankele Monastery",
    "Kokila Ella Waterfall",
    "Ridee Viharaya Cave Temple",
    "Kurunegala Buddha Statue",
    "Deduruoya Reservoir Dam",
    "Wariyapola Temple Circuit",
    "Angilimala maha saya"
  ],

  // 201 - 220
  [
    "Adam's Bridge (Ram Setu)",
    "Mannar Island",
    "Baobab Tree Mannar",
    "Mannar Fort",
    "Thiruketheeswaram Temple",
    "Talaimannar Pier",
    "Vankalai Sanctuary",
    "Mannar Beach",
    "Doric Bungalow Arippu",
    "Giant's Tank",
    "Pesalai Fishing Village",
    "Murunkan Rural Area",
    "Silavathurai Beach",
    "Vidataltivu Nature Reserve",
    "Arippu Beach",
    "Dambulla Cave Temple",
    "Sigiriya Rock Fortress",
    "Pidurangala Rock",
    "Nalanda Gedige",
    "Riverston",
    "Pitawala Pathana",
    "Sera Ella Falls",
    "Bambarakiri Ella",
    "Thelgamu Oya",
    "Knuckles Mountain Range (Matale side)",
    "Wasgamuwa National Park",
    "Aluvihare Rock Temple",
    "Euphoria Spice and Herbal Garden",
    "Sri Muthumariamman kovil Matale",
    "Sudu Ganga",
    "Lakegala Mountain",
    "Manigala",
    "Mini World’s End Riverston",
    "Rathinda Falls",
    "Dothalugala Nature Trail",
    "Campbell’s Lane Forest Reserve",
    "Hunasgiriya (Matale side access)",
    "Elkaduwa Tea Estate",
    "Corbett’s Gap",
    "Mirissa Beach",
    "Polhena Beach",
    "Matara Fort",
    "Star Fort Matara",
    "Dondra Head Lighthouse",
    "Weherahena Temple",
    "Devinuwara Temple",
    "Nilwala River",
    "Parrot Rock Mirissa",
    "Coconut Tree Hill Mirissa",
    "Madiha Beach",
    "Lakshawaththa Beach",
    "Weligama Beach",
    "Taprobane Island",
    "Kushtarajagala Statue",
    "Secret Beach Mirissa",
    "Turtle Bay Weligama",
    "Midigama Beach",
    "Ahangama Beach",
    "Parey Dewa Temple",
    "Dickwella Beach",
    "Hiriketiya Beach",
    "Blue Beach Island",
    "Gandara Beach",
    "Maduru Oya National Park",
    "Gal Oya National Park (border access)",
    "Nilgala Forest Reserve",
    "Dambana Veddha Village",
    "Buduruwagala Temple",
    "Maligawila Buddha Statue",
    "Yudaganawa Archaeological Site",
    "Kebiliththa Sacred Area",
    "Handapanagala Lake",
    "Ethimale Temple",
    "Huluganga Falls",
    "Wedikumbura Temple",
    "Lunugamvehera National Park (border access)",
    "Diyaluma Falls (border access)",
    "Kataragama (border proximity region)",
    "Kataragama kiri wehera",
    "Bibile Forest Area",
    "Siyambalanduwa Region",
    "Wellawaya Scenic Area",
    "Hambegamuwa Tank",
    "Mullaitivu Beach",
    "Mullivaikkal Beach",
    "Nanthikadal Lagoon",
    "Nayaru Lagoon",
    "Kokkilai Lagoon",
    "Kokkilai Bird Sanctuary",
    "Alampil Beach",
    "Chalai Beach",
    "Vattappalai Kannaki kovil",
    "Thannimurippu Kulam",
    "Oddusuddan Area",
    "Puthukkudiyiruppu Area",
    "Mullaitivu War Memorial Area",
    "Iranapalai Lagoon",
    "Kokuthoduvai Coast",
    "Ampalavanpokkanai",
    "Udaiyarkaddu Lagoon"
  ],

  // 301 - 320
  [
    "Nayaru Beach",
    "Mullaitivu Town Beach Park",
    "Alampil Mangrove Area",
    "Kokkilai Coastal Belt",
    "Mullivaikkal Memorial Area",
    "Karunattukerni Area",
    "Gregory Lake",
    "Horton Plains National Park",
    "World’s End",
    "Mini World’s End",
    "Hakgala Botanical Garden",
    "Victoria Park Nuwara Eliya",
    "Lover’s Leap Waterfall",
    "Ramboda Falls",
    "Devon Falls",
    "St. Clair’s Falls",
    "Moon Plains/ Sandathenna",
    "Galway’s Land National Park",
    "Seetha Amman kovil",
    "Single Tree Hill",
    "Ambewela Farm",
    "Labookellie Tea Centre",
    "Bomburu Ella Falls",
    "Pidurutalagala Mountain",
    "Kande Ela Reservoir",
    "Blackpool Bridge",
    "Nanu Oya",
    "Strawberry Farms Nuwara Eliya",
    "Shanthipura Viewpoint",
    "Polonnaruwa Ancient City",
    "Gal Vihara",
    "Parakrama Samudraya",
    "Rankoth Vehera",
    "Vatadage",
    "Lankatilaka Image House",
    "Tivanka Image House",
    "Kiri Vehera",
    "Nelum Pokuna",
    "Minneriya National Park",
    "Kaudulla National Park",
    "Girithale Tank",
    "Medirigiriya Vatadage",
    "Somawathiya Chaitya",
    "Angammedilla National Park",
    "Demala Maha Seya",
    "Pabalu Vehera",
    "Siva Devalaya No.1",
    "Siva Devalaya No.2",
    "Royal Palace of King Parakramabahu",
    "King Nissanka malla Audience Hall",
    "Kumara Pokuna",
    "Polonnaruwa Museum",
    "Wilpattu National Park",
    "Kalpitiya Beach",
    "Kalpitiya Lagoon",
    "Bar Reef Marine Sanctuary",
    "Dutch Fort Kalpitiya",
    "St. Anne’s Shrine Talawila",
    "Anawilundawa Wetland Sanctuary",
    "Puttalam Lagoon",
    "Baththalangunduwa Island",
    "Alankuda Beach",
    "Norochcholai Beach",
    "Mampuri Island",
    "Sinnapadu Beach",
    "Puttalam Salt Pans",
    "Kudawa Beach",
    "Kandakuliya Beach",
    "Talawila Beach",
    "Chilaw Beach",
    "Munneswaram Kovil",
    "Deduru Oya",
    "Iranawila Beach",
    "Dutch Canal Puttalam",
    "Holy Cross National Shrine Marawila",
    "Sinharaja Forest Reserve",
    "Udawalawe National Park (border access)",
    "Adam’s Peak (Sri Pada)",
    "Bopath Ella",
    "Kirindi Ella",
    "Katugas Ella Falls",
    "Diyawini Ella",
    "Waulpane Cave",
    "Ratnapura Gem Mines",
    "Batadombalena Cave",
    "Kuragala Ancient Site",
    "Rajawaka Falls",
    "Belihuloya",
    "Horton Plains (access side)",
    "Saman Devalaya",
    "Nonpareil Estate",
    "Bambarakanda Falls (nearby access)",
    "Surathali Ella",
    "Lanka Ella (Belihuloya)",
    "Galagama Falls",
    "Kalawana Forest Area",
    "Pelmadulla Area",
    "Balangoda Scenic Area",
    "Rakwana Mountain Area",
    "Deniyaya (border rainforest access)",
    "Nilaveli Beach",
    "Uppuveli Beach",
    "Pigeon Island National Park",
    "Koneswaram Temple",
    "Fort Frederick",
    "Marble Beach",
    "Kanniya Hot Water Wells",
    "Trincomalee Harbour",
    "Lovers Leap, Trinco",
    "Swami Rock",
    "Velgam Vehera",
    "Seruwawila Mangala Raja Maha Viharaya",
    "Kuchchaveli Beach",
    "Coral Cove",
    "Pulmoddai Beach",
    "Foul Point Lighthouse- Sampur",
    "Dutch Bay Beach",
    "Back Bay Beach",
    "Trincomalee War Cemetery",
    "China Bay Beach",
    "Cod Bay Fishery Harbour",
    "Vavuniya Tank",
    "Madukanda Viharaya",
    "Periyakulam Tank",
    "Cheddikulam Tank",
    "Vavuniya Town Park",
    "Vavuniya Water Park",
    "Omanthai Pillaiyar Kovil",
    "Nedunkeni Forest Area",
    "Maravankulam",
    "Siththivinayagar Kovil",
    "Andankulam Tank",
    "Sapumalgaskada Buddhist Monastery",
    "Sri Dalada Viharaya Madukanda",
    "Kandasamy Kovil",
    "Archeological Museum of Vavuniya",
    "Grand Jumma Mosques, Vavuniya",
    "Kalvari Church, Vavuniya"
  ]
];