# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "Travel Plan Assistant"
remote_theme: cepdnaclk/eYY-project-theme
description: "AI-Powered Algorithmic Trip Planner & Smart Corridor Navigator | Department of Computer Engineering, University of Peradeniya"
markdown: kramdown

kramdown:
  parse_block_html: false
  syntax_highlighter_opts:
    block:
      line_numbers: false
